from test_helpers import assert_equal_phonetics

def test_kvp_au():
    assert_equal_phonetics("KVP", "འཽ་", "au")
    assert_equal_phonetics("KVP", "འཽ་རེ་", "auré")
    assert_equal_phonetics("KVP", "ཨཽ", "au")
    assert_equal_phonetics("KVP", "ཨཽ་དུམ་", "audum")
    assert_equal_phonetics("KVP", "ཨཽག་", "auk")
    assert_equal_phonetics("KVP", "ཨཽག་ཆོས", "augchö")
    assert_equal_phonetics("KVP", "ཨཽང་", "aung")
    assert_equal_phonetics("KVP", "ཨཽང་གུ", "aungu")
    assert_equal_phonetics("KVP", "ཨཽར་", "aur")
    assert_equal_phonetics("KVP", "ཨཽར་ཤིང", "aurshing")
    assert_equal_phonetics("KVP", "བཽ", "bau")
    assert_equal_phonetics("KVP", "བཽ་ཧ་", "bauha")
    assert_equal_phonetics("KVP", "དྲཽག", "drauk")
    assert_equal_phonetics("KVP", "གཽ", "gau")
    assert_equal_phonetics("KVP", "གཽ་ཏ་", "gauta")
    assert_equal_phonetics("KVP", "ཀཽ", "kau")
    assert_equal_phonetics("KVP", "ཀཽ་མུ་", "kaumu")
    assert_equal_phonetics("KVP", "ཀཽན་", "kaun")
    assert_equal_phonetics("KVP", "ཀཽན་ཏི་", "kaunti")
    assert_equal_phonetics("KVP", "མཽ", "mau")
    assert_equal_phonetics("KVP", "མཽ་གལ་", "maugal")
    assert_equal_phonetics("KVP", "མཽད", "maud")
    assert_equal_phonetics("KVP", "མཽད་གལ", "maudgal")
    assert_equal_phonetics("KVP", "པཽ", "pau")
    assert_equal_phonetics("KVP", "པཽ་ལོ་", "paulo")
    assert_equal_phonetics("KVP", "སཽ", "sau")
    assert_equal_phonetics("KVP", "སཽ་མ", "sauma")
    assert_equal_phonetics("KVP", "ཏཽ་", "tau")
    assert_equal_phonetics("KVP", "ཏཽ་ར་", "taura")
    assert_equal_phonetics("KVP", "ཙཽ་", "tsau")
    assert_equal_phonetics("KVP", "ཙཽ་ར", "tsaura")